# Generated by Django 2.2.3 on 2019-08-29 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_genre', models.CharField(max_length=200)),
                ('genre_summary', models.CharField(max_length=200)),
                ('genre_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='FilmSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('film_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.FilmGenre', verbose_name='Genre')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=200)),
                ('film_content_review', models.TextField()),
                ('review_published', models.DateTimeField(default=datetime.datetime(2019, 8, 29, 7, 49, 4, 664804), verbose_name='date published')),
                ('film_slug', models.CharField(default=1, max_length=200)),
                ('film_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.FilmSeries', verbose_name='Series')),
            ],
            options={
                'verbose_name_plural': 'Films',
            },
        ),
    ]
