# Generated by Django 2.2.3 on 2019-08-29 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 7, 50, 28, 918187), verbose_name='date published'),
        ),
    ]
