# Generated by Django 2.2.3 on 2019-08-29 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190829_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 8, 5, 12, 715950), verbose_name='date published'),
        ),
    ]
