# Generated by Django 2.2.3 on 2019-08-29 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190829_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmgenre',
            name='genre_slug',
            field=models.SlugField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='films',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 8, 18, 25, 46080), verbose_name='date published'),
        ),
    ]
