# Generated by Django 2.2.3 on 2019-08-29 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190829_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmgenre',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.RenameField(
            model_name='filmseries',
            old_name='film_category',
            new_name='film_genre',
        ),
        migrations.AlterField(
            model_name='filmgenre',
            name='genre_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='films',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 9, 44, 29, 359318), verbose_name='date published'),
        ),
    ]
