# Generated by Django 2.2.3 on 2019-09-10 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190910_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 9, 24, 35, 576211), verbose_name='date published'),
        ),
    ]
